### PR TITLE
Fix/console errors

### LINKED ISSUE #14: [Rework] Fix Errors
# Mapbox

#### Additional Notes
Might be something to do with a deprecated version of Mapbox, or something missing during refactor.
Needs to be fixed ASAP. Might want to consider updating Mapbox anyway if it is an old version.

[ ] Move mapbox API KEY into environmental files for safety reasons

### PR DESCRIPTION
**Pull request by cadrianxyz**
# Description

Very bad fix of console errors, some of the problems are underlying problems that have to do with the app logic (using event bus for modals used only in one page, etc). Will need a bunch more refactoring. The modal issue will be solved with the removal of modal once an for all in #18 

Looks like a bunch of changes but all that really matters is in `./Discover`, `./ExploreBar`, and `./createEventModal`

Fixes #14 

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. If design change, please ensure design change/addition has been approved by a UX Lead or 

- [ ] Visual UX Approval

# Checklist:

- [ ] Code follows the project's style guidelines
- [x] I have performed a self-review of the Code being pushed
- [ ] Code has been reviewed by at least one other developer
- [x] Code has appropriate commenting, particularly in hard-to-understand areas
- [x] Corresponding changes to the documentation have been made
- [x] The changes generate no new warnings

### CODE REVIEW

**Comment by cadrianxyz** [comment]
@kraytaps Want to move the mapbox access key into a `dotenv` file, but this will be another breaking change (everyone needs to update). Honestly I want to do it in this PR instead of having to do another one, what u think?

File: src/components/map/Mapbox.vue [hunk 1]
```diff
@@ -7,7 +7,7 @@
     :mapStyle     = "mapStyle"
     :center       = "defaultMapStyle.center"
     :zoom         = "defaultMapStyle.zoom"
-    @load         = "onMapLoad"
+    @load         = "onMapLoaded"
```
Comment (kraytaps) [inline src/components/map/Mapbox.vue:10]: do we not pass in a parameter to this function reference

**Review by kraytaps — APPROVED** [review]
Mapbox load was coded according to documentation and I'm assuming all the svgs are from the mapbox library
